-- Optional demo: run once in Console > Data > default > SQL.
-- Leave "Track this" enabled, or track public.starter_notes afterwards.
-- Deliberately fail if the table already exists; never overwrite existing data.
BEGIN;
CREATE TABLE public.starter_notes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL CHECK (length(title) BETWEEN 1 AND 200),
  completed boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO public.starter_notes (title) VALUES
  ('Try a GraphQL query'),
  ('Update a note with a mutation'),
  ('Watch changes with a subscription');
COMMIT;
